spring.application.name=mealplanner

spring.datasource.url=jdbc:postgresql://localhost:5432/mealplanner
spring.datasource.username=mealplanner
spring.datasource.password=mealplanner

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
